### ISSUE TITLE
Console spam V3.6

### ISSUE THREAD

**Issue by BiGUNMAN** [Armarr/Autorank-2#250] opened 2015-08-09 22:40 UTC
On startup of the new autorank it spammed:

[18:39:02] [Craft Scheduler Thread - 10/WARN]: [Autorank] Could not get player name of uuid '64ec5dee-82a3-4df0-82cc-79f329f48668'!

For all uuids in the database..

**Comment by CathalCraft** [comment] 2015-08-14 09:27
Same issue here.

**Comment by Staartvin** [comment] 2015-08-14 13:33
Only for that player?

**Comment by CathalCraft** [comment] 2015-08-14 21:30
My messages are a bit different than his.

[04:53:59] [Thread-2591/INFO]: [Autorank] Could not fetch UUID of player 'bAllerForLifE44'!
[04:53:59] [Thread-2592/INFO]: [Autorank] Could not fetch UUID of player 'bAllerForLifE44'!
[04:53:59] [Thread-2593/INFO]: [Autorank] Could not fetch UUID of player 'fearmymoves'!
[04:53:59] [Thread-2594/INFO]: [Autorank] Could not fetch UUID of player 'fearmymoves'!
[04:53:59] [Thread-2595/INFO]: [Autorank] Could not fetch UUID of player 'SharkBoy__'!
[04:53:59] [Thread-2596/INFO]: [Autorank] Could not fetch UUID of player 'SharkBoy__'!

I use flatfiles, and it does that for EVERY player in the database.

There are 22831 players in my database. The backup data files are the exact same as the ones after the update, so it shouldn't have to re-lookup the UUIDs.

**Comment by OldTownMC** [comment] 2015-08-14 22:28
@Staartvin It does it for all my players (over 11,500), flatfile.

**Comment by Staartvin** [comment] 2015-08-14 22:34
Okay, so I think I know what the problem is. It's probably on my end, so I'll go to work and try to fix it!
Can both of you post your uuid folder including all the uuids to me? I need those for testing.

**Comment by CathalCraft** [comment] 2015-08-15 00:01
Here you go: http://puu.sh/jBRZH/f57378387e.zip

**Comment by MrDrummer** [comment] 2015-08-18 16:00
@Staartvin Same issue here. (I am using mySql to connect to stats) On startup the uuids get spammed, for now i am just using the last version, until this gets fixed :)

**Comment by rickygwapo** [comment] 2015-08-19 05:36
This update got me really annoyed, my playerheads are not showing anymore due to autorank having to lookup about hhmmm 30,000 players of mine. i can re-use the old autorank.jar right? without any problems. i hate the newest one

**Comment by CathalCraft** [comment] 2015-08-19 06:40
Yes, you can use the older version.

**Comment by OldTownMC** [comment] 2015-08-19 16:02
Should I still get your my UUID folder (forgot about it, but can do so quickly if necessary).

**Comment by Staartvin** [comment] 2015-08-28 16:09
Yeah, still get the UUID folder. The more data I can test it with, the better!

**Comment by TheCanadianIdiot** [comment] 2015-09-01 21:10
Same issue here, I had to downgrade on 2 occasions to fix this, please help.

**Comment by OldTownMC** [comment] 2015-09-06 04:27
https://drive.google.com/file/d/0B84r0bGDfW26UlB4WkxIdkExQm8/view?usp=sharing

**Comment by Staartvin** [comment] 2015-09-07 19:38
This is fine ;)

**Comment by CathalCraft** [comment] 2015-09-07 21:47
Does Build #435 have a possible fix for this issue?

**Comment by Staartvin** [comment] 2015-09-07 21:49
Yes, it does, but it is not tested extensively so proceed with caution. Make sure to backup before using it.

**Comment by dwilson390** [comment] 2015-09-20 14:57
Hey there,

Exact same issue, been bugging me for a quite a while, so I decided to checkup here, seems it's not me as I originally thought.

Will we see a fix for this anytime soon?

Thanks!

**Comment by Staartvin** [comment] 2015-09-20 20:56
Are you also running 3.6?

**Comment by dwilson390** [comment] 2015-09-21 18:20
I am, yes.

**Comment by dwilson390** [comment] 2015-09-26 17:46
Any update as of yet? Issue is still reproducible.

**Comment by Staartvin** [comment] 2015-09-26 18:49
I've worked on this a few dev builds earlier. I implemented an algorithm that checks the amount of UUIDs that need to be checked. This is already in place. Could you try the latest dev build?

**Comment by dwilson390** [comment] 2015-09-27 19:58
Should it be stable enough?

**Comment by Staartvin** [comment] 2015-09-28 05:51
Always back up, just in case. That's recommended for any upgrade.

**Comment by dwilson390** [comment] 2015-10-14 18:37
Sorry for long response time however everything seems to be fixed on the latest dev build.  Just wondering what these errors mean?

```
14.10 18:34:14 [Server] WARN Could not get player name of uuid 'ae40e2be-fb4e-4b9e-8487-55c20e9958d8'! 14.10 18:34:15 [Server] INFO Join » djwilsondylan connected to Survival 14.10 18:34:15 [Server] WARN Could not get player name of uuid '2a597861-ad71-4092-8ae7-eb23fef53434'! 14.10 18:34:16 [Server] INFO &0 14.10 18:34:16 [Server] WARN Could not get player name of uuid 'beef6f1f-d549-4ee8-80e3-9f8e918bfca6'! 14.10 18:34:17 [Server] WARN Could not get player name of uuid 'ca2c9669-ed7f-42c5-9043-200f71e05576'! 14.10 18:34:17 [Server] WARN Could not get player name of uuid 'cdd6897a-9a82-4711-a5c9-19a1ecde9e96'! 14.10 18:34:17 [Server] WARN Could not get player name of uuid '197ce550-b4eb-4e01-8f89-7e9aaa3564b0'! 14.10 18:34:17 [Server] WARN Could not get player name of uuid '4bfaa292-d270-4a08-add3-279c7abaf390'! 14.10 18:34:17 [Server] WARN Could not get player name of uuid 'd840a62d-7d39-4dde-abfa-58b9f6ae6f0f'! 14.10 18:34:19 [Server] INFO Config files have been correctly setup!
```

**Comment by Ironic8b498** [comment] 2015-12-21 20:10
I have same problem:

https://dl.dropboxusercontent.com/u/81218539/uuids.zip

[14:50:52] [Craft Scheduler Thread - 5/WARN]: [Autorank] Could not get player name of uuid 'c18144b1-3002-41da-9551-dfebab6b475e'!
[14:50:52] [Craft Scheduler Thread - 5/WARN]: [Autorank] Could not get player name of uuid '02abd7b3-7f92-487d-87c4-21cc62a0c2a7'!
[14:50:52] [Craft Scheduler Thread - 5/WARN]: [Autorank] Could not get player name of uuid '598135af-ae01-47e0-9f27-0cf9a380006f'!
[14:50:56] [Craft Scheduler Thread - 1/INFO]: [Autorank] Config files have been correctly setup!
[14:50:57] [Craft Scheduler Thread - 5/WARN]: [Autorank] Could not get player name of uuid '940aee8c-fcdd-4e74-9c3d-05881f5de07c'!
[14:50:57] [Craft Scheduler Thread - 5/WARN]: [Autorank] Could not get player name of uuid '9f6ba6af-85ce-46f6-a5a5-f0085263669a'!

**Comment by Staartvin** [comment] 2016-04-12 13:53
Closed due to inactivity.

**Closed by Staartvin** 2016-04-12 13:53 UTC
