### ISSUE TITLE
Suddently Ar leaderboard isn't showing me anymore.

### ISSUE THREAD

**Issue by Nesseley** [Armarr/Autorank-2#282] opened 2016-01-12 21:16 UTC
Hey!
Recently this started to spam in my console.
12.01 22:03:30 [Server] INFO Could not fetch UUID of player 'Inferi'!
12.01 22:03:29 [Server] INFO Could not fetch UUID of player 'Inferi'!
12.01 22:03:29 [Server] INFO Could not fetch UUID of player 'Erikp98'!
12.01 22:03:29 [Server] INFO Could not fetch UUID of player 'Erikp98'!
12.01 22:03:29 [Server] INFO Could not fetch UUID of player 'Kriss005'!
12.01 22:03:29 [Server] INFO Could not fetch UUID of player 'Kriss005'!

This goes on and on with ALOT of players.

And now with no error, I suddently no loner show in /ar leaderboard. I have the most ontime, but now im gone. When i use /ar check it says i have 27days wich is correct, but ar leaderboard doenst show me.
A restart semes to fix the problem, but this is an issue.
/ar leaderboard also takes a LONG time to load, while /ar check and all other commands are normal.

**Comment by Staartvin** [comment] 2016-01-12 22:03
This means the players in the uuids.yml are not up to date or corrupt. I'm not sure why it is fixed after restarting though, that's weird.

**Comment by Nesseley** [comment] 2016-01-13 15:23
Nesseley:
  uuid: 959429c2-b123-4c1e-827b-1e1a7c16b731
  updateTime: 1452697922422

This is my user and UUID. Correct information.
But keeps spamming "Could not fetch UUID of player" in console.. 
This _sometimes_ starts after /ar leaderboard has ben used.


Got this error when i stopped my server right now.
http://pastebin.com/bWWXKxV4

When i start the server it says that it is correct set up.
"[16:21:33] [Craft Scheduler Thread - 4/INFO]: [Autorank] Config files have been correctly setup!"

Hopefully this helps you find out what is wrong. :)

**Comment by Nesseley** [comment] 2016-01-13 15:39
After this restart more people dissapeared from the Leaderboard.
Now I can't find their time using /ar check player
But in the files I can see their name both in Playerdata and UUIDS_X

**Comment by Staartvin** [comment] 2016-01-14 23:51
Could you provide your data.yml via pastebin or mediafire?

**Comment by Nesseley** [comment] 2016-01-15 07:29
Here you go: http://pastebin.com/zBRh67pR
Also I did use /ar archieve 55m yesterday too see if that was a problem with too many users (removed 600) But it still has the same problems. :)

**Comment by Staartvin** [comment] 2016-01-15 21:10
So, I changed the way Autorank deals with leaderboard updating. It can still take a while (I tested it with 22000 uuids), but it caches the complete leaderboard and refreshes it every 30 minutes. If it detects UUIDs that are in the data.yml but not in the uuid files, it will do nothing until that specific player logs in.

**Comment by Staartvin** [comment] 2016-01-15 21:16
Try downloading dev build #457: http://62.131.38.74:8080/job/Autorank/457/

**Comment by Nesseley** [comment] 2016-01-16 09:05
Tried out the build now! No errors so far!
Will def. wirght back if something pops up.
(This also fixed the " Could not fetch UUID of player 'player'!" spam btw)

I still would like to check players /ar check player when they are offline since last restart thoe, still no fix for this? I don't understand why this happens when the player is in all the right files :/

**Comment by Staartvin** [comment] 2016-01-16 11:09
Could you describe what you see when you perform /ar check? What happens? Could you also send your most recent data.yml and all uuid files in your uuids folder?

**Comment by Nesseley** [comment] 2016-01-16 11:40
This is /ar leaderboard and /ar check
https://gyazo.com/4a7ceaff21d546d4cfa4517aef68a9da
As you see Radwolf_ma is showing in leaderboard but I can not find her with /ar check

data.yml: http://pastebin.com/XcjYi5kE
UUID: https://drive.google.com/open?id=0B13b2ZkHMNKqemp2VU9vUW0tTUk

**Comment by Staartvin** [comment] 2016-01-16 11:52
Hmm, I think this bugged slipped in yesterday, it did work before. Anyway, good find. I'll fix it for you.

**Comment by Nesseley** [comment] 2016-01-16 11:54
Awesome, I havent found any other bugs with this build so you can maybe try to release it more public! Its a nice fix to the UUID spam that I have seen more people asking about. Il try the one you make now, and tell you back if it works as it should. :)

**Comment by Staartvin** [comment] 2016-01-16 11:55
It'll just take a few minutes ;)

**Comment by Staartvin** [comment] 2016-01-16 12:55
Okay, so obviously it will take a bit longer, I found unexpected behavior of Bukkit, so I'll have to change Autorank to work around this.

**Comment by Staartvin** [comment] 2016-01-16 12:58
Can you try build 466?

**Comment by Nesseley** [comment] 2016-01-16 16:22
Paste me the link and Il give it a try :)

**Comment by Staartvin** [comment] 2016-01-16 16:26
http://62.131.38.74:8080/job/Autorank/lastSuccessfulBuild/

**Comment by Nesseley** [comment] 2016-01-16 18:30
Havent tried the new build yet!! (Too many players online, and i don't dare to angry them)
Got this error on first build you gave me: http://pastebin.com/sucQfsv5
Do you think this is fixed in new build?

**Comment by Staartvin** [comment] 2016-01-16 18:36
Could you give me your IP? I would like to join to see if all is working well :)

**Comment by Staartvin** [comment] 2016-01-16 18:37
Also, do you have Skype or something? It would be handy to talk through there.

**Comment by Nesseley** [comment] 2016-01-16 18:42
mc.Konsole.no join and il send skype form there. :)

**Comment by Nesseley** [comment] 2016-01-16 22:32
Got the error again, sent you the logfiles on Skype.

**Comment by Nesseley** [comment] 2016-01-17 14:00
Found a thing that got ruined in the lastet update.
Leaderboard now shows everyone in lowercase.
"nesseley" instead of "Nesseley" and so on.

**Comment by Staartvin** [comment] 2016-01-17 14:04
This is due to the fact that players are now stored in lowercase in the data.yml. I might find a way around this, but I'm not sure.

**Comment by Staartvin** [comment] 2016-01-25 21:31
Fixed in Autorank 3.7.1!

**Closed by Staartvin** 2016-01-25 21:31 UTC
